#!/usr/bin/env bash
# adding a custom http header

#installing nginx

sudo apt update -y -qq
sudo apt install nginx -y -qq

new_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
		root /var/www/html;
	index index.html index.html index.nginx-debian.html;
	server_name _;
	add_header X-Served-By $hostname;
}
"
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default

echo "$new_config" > /etc/nginx/sites-available/default

sudo service nginx restart
