#!/usr/bin/env bash
# Installing Nginx and redirecting

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html

echo -e "Hello redirection" > /var/www/html/index.nginx-debian.html
sudo sed -i '24i        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
echo -e "\n Completed\n"
